spring:
  application:
    name: spring_jpa
  datasource:
#    REALIZANDO CONECÇÃO COM O BANCO
    url: jdbc:postgres://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

